name: yumyum_amicta
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  carousel_slider: ^4.0.0
  google_fonts: ^6.1.0
  url_launcher: ^6.2.5
  intl: ^0.18.1
  another_flushbar: ^1.12.30
  equatable: ^2.0.3
  http: ^1.0.0
  flutter_slidable: ^3.0.0
  get: ^4.6.6
  expansion_tile_group: ^1.2.4
  lite_rolling_switch: ^1.0.1
  get_storage: ^2.1.1
  localstore: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/